### ISSUE TITLE
Annotation download ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by mbiemans** [dmis-lab/BERN2#11]
Hi,

First of all, thanks for the great work! 

I tried to download the pre-processed PubMed annotations, but got a server error: ERR_EMPTY_RESPONSE. Is there any other way to download the data?

**Comment by mjeensung** [comment]
Hi @mbiemans 

Thank you for letting us know.
I found that the file server is currently down due to a lot of requests.
I'll let you know as soon as the file server works again.

**Comment by minstar** [comment]
Hi @mbiemans

Thank you for waiting us.
Now, you can easily get the pre-processed PubMed annotations on our server.
```wget http://nlp.dmis.korea.edu/projects/bern2/annotations/annotation_v1.1.tar.gz```

Please let us know when you have problems!

**Comment by mbiemans** [comment]
Thanks for your reply! Unfortunately, it seems that the server is down again.

**Comment by mjeensung** [comment]
@mbiemans 

Sorry for the inconvenience. 
We've decided to upload the annotations to google drive instead because our file server is currently unstable.

Aside from that, an issue has been found in the uploaded annotations (https://github.com/dmis-lab/BERN2/issues/12), so we are going to upload the new annotations after fixing it.

**Comment by mjeensung** [comment]
Hi, @mbiemans 

Many thanks for your patience.
We've just uploaded [annotation_v1.0.tar.gz](https://nlp.dmis.korea.edu/projects/bern2-sung-et-al-2022/annotation_v1.0.tar.gz) generated by [BERN2 v1.0](https://github.com/dmis-lab/BERN2/releases/tag/v1.0.0). We've also improved the stability of our file server, so hopefully, the annotations will be downloaded without a server issue. Please let us know if you have any troubles downloading it.

For more details, please see [here](https://github.com/dmis-lab/BERN2#annotations).

**Comment by mbiemans** [comment]
Great, thanks for your time! Unfortunately, I still cannot manage to download the annotations due to the same error.

**Comment by mjeensung** [comment]
My bad!
I updated the URL. It should've started with http, not with https.
(http://nlp.dmis.korea.edu/projects/bern2-sung-et-al-2022/annotation_v1.0.tar.gz)
Could you try it again?

**Comment by mbiemans** [comment]
Thanks very much, that works!
