### ISSUE TITLE
Files are duplicated with same PMID

### ISSUE THREAD

**Issue by ksj20** [dmis-lab/BERN2#12]
There are major issues in the data. 
Many files were just duplicates of one PMID's labelling. Is this intentional?
I list the files of problem, and the pmid that it is filled up with in a table, following up with an example image of the issue.
Look forward to your feedback. 

| file # of problem 21n0XXX  |  file is filled up with only |  
|---|---|
|  713, 714, 715, 716, 717, 718, 719 | pmid: 22137675  | 
|  740, 741, 742 |   pmid: 23065850 | 
|   748, 749 |   pmid: 23334882 |
|  758, 759 | pmid: 23630654 |
| 766, 767 | pmid: 23886943 | 
| 779, 780, 781, 782 | pmid: 24335088 | 
| 788, 789, 790, 791 | pmid: 24595986 | 
| 813, 812, 811, 810 | pmid: 25329600 |

example image (21n0713.json) 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/43039430/152906704-55f5ae06-68e4-4da3-9a79-ad80671c07b8.png)

**Comment by minstar** [comment]
Thank you for let us know this issue.
This wasn't intended in our case.
We will check and clarify this issue.

**Comment by minstar** [comment]
@ksj20 
We identified that some files are duplicated with the same PMID.
We will notify you after we process all these files.
Sorry for the inconvenience.

**Comment by ksj20** [comment]
In addition, I would also like to point out a couple more things:

- could you check if there are any empty files? there were 0 kb files
- could you provide the data excluding either the "_id" value or "pmid"? I think they are identical

Thanks

**Comment by minstar** [comment]
We also check that there are empty files and we will manage this either.
For the key "_id" and "pmid" is the same value.
In our database, we have to make an independent key to recognize PubMed ids.
we would consider removing the "_id" key for the publishing version.

Thank you!

**Comment by ksj20** [comment]
When will the published data be available?

**Comment by minstar** [comment]
@ksj20 
Sorry for the inconvenience.

We have identified some errors (e.g., mutation span error) which could affect our annotated PubMed files.
Thus, we decided to annotate all these files from scratch. 
It will take at least one month in our guess.

**Comment by mjeensung** [comment]
Hi, @ksj20 

Many thanks for your patience.
After fixing the two issues that you mentioned, duplicate PMIDs and empty files, we updated [annotation_v1.0.tar.gz](https://nlp.dmis.korea.edu/projects/bern2-sung-et-al-2022/annotation_v1.0.tar.gz) generated by [BERN2 v1.0](https://github.com/dmis-lab/BERN2/releases/tag/v1.0.0). For more information, please see [here](https://github.com/dmis-lab/BERN2#annotations).

To make it clear, the annotations mentioned by @minstar above will be generated by [BERN2 v1.1](https://github.com/dmis-lab/BERN2/releases/tag/v1.1.0) soon.

**Comment by Vin0dManne** [comment]
Thanks for updated annotations. May I know on what system config it took 1 month to re-run. Reason to ask - I would like to run on my system.

**Comment by mjeensung** [comment]
Hi @Vin0dManne 

Thanks for your patience.

We're currently annotating 33M abstracts (pubmed22n0001 –1114) by running four BERN2s at the same time.
As we stated in our paper, annotating one abstract takes about 300ms. In short, 33M * 0.3 sec / 4 / 60 / 60/ 24 equals approximately a month. 

For more details of our system config, we're using Ubuntu 18.04.5 LTS as an OS, two titan XPs (12GB * 2) as GPUs.
If there's more information you need, please feel free to ask us.
