### ISSUE TITLE
fail to install BERN2 locally

### ISSUE THREAD

**Issue by yuanhao96** [dmis-lab/BERN2#18]
Fail to follow the installation guidelines in readme:
git clone git@github.com:dmis-lab/BERN2.git

Cloning into 'BERN2'...
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by mjeensung** [comment]
Hi @yuanhao96 

Thanks for your interest in our work.
Could you please try http://nlp.dmis.korea.edu/projects/bern2-sung-et-al-2022/annotation_v1.0.tar.gz again?

**Comment by yuanhao96** [comment]
It works this time! Thanks!
