### ISSUE TITLE
Entity normalization without NER

### ISSUE THREAD

**Issue by pedroruas18** [dmis-lab/BERN2#20]
Greetings!

I was wondering if it is possible to use BERN2 only to perform entity linking/normalization, i.e., to input a list of already recognized entities by another tool and then normalize the entities?

Thank you

**Comment by mjeensung** [comment]
Hi @pedroruas18 

For the entity normalization, we used BioSyn (https://github.com/dmis-lab/BioSyn#predictions-top-5).

There's an example of how to use BioSyn to normalize an entity when given an input mention.
By slightly modifying the script, I think you can use it as you described.
