### ISSUE TITLE
bash run_bern2.sh

### ISSUE THREAD

**Issue by venkateshkolli** [dmis-lab/BERN2#22]
I have the following error when trying to run the command in the title.:

mkdir: cannot create directory ‘logs’: File exists
nohup: failed to run command 'python': No such file or directory
nohup: failed to run command 'python': No such file or directory
nohup: failed to run command 'python': No such file or directory
Traceback (most recent call last):
  File "server.py", line 1, in <module>
    from app import create_app
  File "/mnt/c/Users/kolli/BERN2/app/__init__.py", line 129
    return render_template('result_text.html', result_items=res_items, latency = f'{latency*1000:9.2f}', result_str=json.dumps(result_dict, sort_keys=True, indent=4))
                                                                                                      ^
SyntaxError: invalid syntax

I am trying to solve this error but please help me out with this error. Thank you.

**Comment by mjeensung** [comment]
Hi @venkateshkolli 

What is the python version you are using?
The error is likely due to `f-string`, which has been supported as of Python3.6.
