### ISSUE TITLE
Security Issue block abstract result

### ISSUE THREAD

**Issue by JacopoBandoni** [dmis-lab/BERN2#23]
By providing the following abstract

"Obesity affects over 42% of the United States population and exacerbates heart disease, the leading cause of death in men and women. Obesity also increases pro-inflammatory cytokines that cause chronic tissue damage to vital organs. The standard-of-care does not sufficiently attenuate these inflammatory sequelae. Angiotensin II receptor AT2R is an anti-inflammatory and cardiovascular protective molecule; however, AT2R agonists are not used in the clinic to treat heart disease. NP-6A4 is a new AT2R peptide agonist with an FDA orphan drug designation for pediatric cardiomyopathy. NP-6A4 increases AT2R expression (mRNA and protein) and nitric oxide generation in human cardiovascular cells. AT2R-antagonist PD123319 and AT2RSiRNA suppress NP-6A4-effects indicating that NP-6A4 acts through AT2R. To determine whether NP-6A4 would mitigate cardiac damage from chronic inflammation induced by untreated obesity, we investigated the effects of 2-weeks NP-6A4 treatment (1.8 mg/kg delivered subcutaneously) on cardiac pathology of male Zucker obese (ZO) rats that display obesity, pre-diabetes and cardiac dysfunction. NP-6A4 attenuated cardiac diastolic and systolic dysfunction, cardiac fibrosis and cardiomyocyte hypertrophy, but increased myocardial capillary density. NP-6A4 treatment suppressed tubulointerstitial injury marker urinary β-NAG, and liver injury marker alkaline phosphatase in serum. These protective effects of NP-6A4 occurred in the presence of obesity, hyperinsulinemia, hyperglycemia, and hyperlipidemia, and without modulating blood pressure. NP-6A4 increased expression of AT2R (consistent with human cells) and cardioprotective erythropoietin (EPO) and Notch1 in ZO rat heart, but suppressed nineteen inflammatory cytokines. Cardiac miRNA profiling and"

We receive the following security error:

"
PAGE BLOCK

Block access - Violation of web security policy
(Blocked - Violation of Web Security Policy)

Sorry. The requested page violates the security policy.

Unallowed special character input or upload file extension may not be appropriate.

If the URL is correct, please try to connect again after a while.

If the same phenomenon continues, Korea University Digital Information Office

Please contact us at (02-3290-4191/4196, ifsea@korea.ac.kr, yellsim@korea.ac.kr).

Connection IP: 131.114.192.226

Blocked path: http://bern2.korea.ac.kr/senddata

When contacting us, please include the blocked time, access IP, and the contents of the accessed URL window.

You can also go to the previous page."

**Comment by Pier297** [comment]
This is the paper in question:

https://pubmed.ncbi.nlm.nih.gov/34220518/

**Comment by mjeensung** [comment]
Hi @JacopoBandoni @Pier297 

Thank you for informing us about the issue!

I was able to reproduce the issue and found that a specific text pattern was not permitted in our web service.
I contacted someone in charge of our web service, so I'll get back to you soon.

**Comment by mjeensung** [comment]
Hi,

This issue was just solved.
Could you try the same input again?
