### ISSUE TITLE
 Confusion about the differences between BERN & BERN2.

### ISSUE THREAD

**Issue by sschet** [dmis-lab/BERN2#26]
Hi, I believe the difference between BERN & BERN2 is that BERN uses ST-NER BioBERT whereas BERN2 uses MT-NER BioLM. Is this correct? My confusion stems from the BioBERT GitHub [(link)](https://github.com/dmis-lab/biobert) where it says BERN uses BioBERT and BERN2 uses BioBERT + BioLM. Any clarification on this would be greatly appreciated. Thanks and I look forward to hearing from you.

**Comment by jhyuklee** [comment]
Hi @sschet, the readme was written a while ago when BERN2 was using BioBERT-based named entity normalization (NEN). Currently BERN2 uses Bio-LM for NER and PubMedBERT for NEN.
