### ISSUE TITLE
Problems encountered trying to run BERN2 in windows

### ISSUE THREAD

**Issue by SatanuG** [dmis-lab/BERN2#29]
Hi,

I have followed all the steps, but when I run the bash script for windows, I get an error. Can you please help me to fix it? 

I have attached a screenshot of the error for your understanding.

Best,
Satanu.

![Screenshot 2022-07-05 100052](https://user-images.githubusercontent.com/39297886/177348300-c1357ffd-e18e-4e7a-bb46-6255318ccac8.png)

**Comment by minstar** [comment]
Thank you for reaching out to us. 

We'll have to see the logs to figure out why the error happens.
The log files are in "logs" folder thus could you check the files and let us know?

Thanks,
Minbyul

**Comment by SatanuG** [comment]
So, I made some changes, and when I tried running from the git bash in a conda environment, the programs started running with three different java applications, but then the python terminal crashed midway. 

Can you please tell me the minimum memory requirement for running this application?

Best,
Satanu.

**Comment by minstar** [comment]
Thank you.

we ran BERN2 locally on an i7-8700 CPU with 16GB RAM.
If you use GPU instead of CPU, you'll need at least 3GB to run in the background.

**Comment by mjeensung** [comment]
If you still have a problem, please feel free to open a new issue. Thank you.
