### ISSUE TITLE
Unable to install bern2 dependencies on Mac OS

### ISSUE THREAD

**Issue by naveenjack** [dmis-lab/BERN2#30]
Hi,

I am trying to install bern2 dependencies on mac Os Montery. When I run the below commands , I am getting package not found error for cudatoolkit and faiss-gpu. And these version are not available for osx. I confirmed it through conda search and also by searching on anaconda.org search packages.

Let me know if I can run this on osx ?

Dependencies :
conda install pytorch==1.9.0 cudatoolkit=10.2 -c pytorch
conda install faiss-gpu libfaiss-avx2 -c conda-forge

Thanks

**Comment by mjeensung** [comment]
Hi, 

thanks for letting us know.
I think it would be better to install faiss-cpu and cudatoolkit which is compatible with the mac os.

**Comment by naveenjack** [comment]
Hi,

Thanks for your reply. Now, I tried installing bern2 on linux machines. Since many packages are compatible this platform. As per the instruction , we need to install pytorch and cudatoolkit (conda install pytorch==1.9.0 cudatoolkit=10.2 -c pytorch). But this version is not available in pytorch channel.  And getting below error:

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/pytorch-1.9.0-py3.7_cuda10.2_cudnn7.6.5_0.tar.bz2>
Elapsed: 00:00.973224

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/linux-64/cudatoolkit-10.2.89-hfd86e86_1.conda>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by naveenjack** [comment]
Adding more details on what I have tried.
**On Mac:**
pytorch=1.9.0 is not available in pytorch channel and cudatoolkit is also not available with 10.2 version. see below commands and result.

$> **conda search pytorch=1.9.0**
Loading channels: done
# Name                       Version           Build  Channel             
pytorch                        1.9.0 cpu_py36h12aac5e_0  conda-forge         
pytorch                        1.9.0 cpu_py36h2d3ebdf_1  conda-forge         
pytorch                        1.9.0 cpu_py36h41aa04d_2  conda-forge         
pytorch                        1.9.0 cpu_py37h6234483_2  conda-forge         
pytorch                        1.9.0 cpu_py37h6472570_0  conda-forge         
pytorch                        1.9.0 cpu_py37hc5e437f_1  conda-forge         
pytorch                        1.9.0 cpu_py38h0529baa_2  conda-forge         
pytorch                        1.9.0 cpu_py38h490fcb8_1  conda-forge         
pytorch                        1.9.0 cpu_py39h28f9090_2  conda-forge         
pytorch                        1.9.0 cpu_py39h37f9f7c_1  conda-forge         
pytorch                        1.9.0 cpu_py39hbc4979b_0  conda-forge 


$> **conda search cudatoolkit=10.2**
Loading channels: done
No match found for: cudatoolkit=10.2. Search: *cudatoolkit*=10.2

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=10.2

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Available channel and version:
**$> conda search cudatoolkit**
Loading channels: done
# Name                       Version           Build  Channel             
cudatoolkit                      9.0      h41a26b3_0  pkgs/main  

**If I have to try bern2 on mac. Then which version of these version has to be installed and from which channels ?**

**On Linux docker image(continuumio/anaconda3)**
**pytorch=1.9.0 cudatoolkit is not available in pytorch**  . And its available with different version and different channel. Please let me know which combination of version and channel has to be used on Linux platform.

(bern2) root@da0f25063715:/# conda search pytorch=1.9.0
Loading channels: done
No match found for: pytorch=1.9.0. Search: *pytorch*=1.9.0

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch=1.9.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

cudatoolkit=10.2 : is not available in pytorch channel and its only available in pkgs/main

(bern2) root@da0f25063715:/# conda search cudatoolkit=10.2
Loading channels: done
# Name                       Version           Build  Channel             
cudatoolkit                  10.2.89      hfd86e86_0  pkgs/main           
cudatoolkit                  10.2.89      hfd86e86_1  pkgs/main
