### ISSUE TITLE
How disable some inner taggers

### ISSUE THREAD

**Issue by mpperez3** [dmis-lab/BERN2#31]
Is it possible to disable some of the internal annotators to improve performance? For example, disable GNORM and work with the other annotators.

Thanks!

**Comment by minstar** [comment]
Thanks for your reaching us!

Yeah, bern2.py in bern2 folder
you could find what you want to get rid of in lines 310-444. 

For example, for named entity recognition, 
line 361-362, you could comment out what you don't want to deal with such as gnormplus (NER).

If you have more questions, feel free to reach us.
