### ISSUE TITLE
Run BERN2 locally on Apple Silicon

### ISSUE THREAD

**Issue by ghostintheshellarise** [dmis-lab/BERN2#33]
I checked the GitHub of the project page.  It requires Nvidia GPU/CUDA to run.  Is there any way that BERN2 can be installed onto an Apple Silicon machine?

Many thanks.

**Comment by minstar** [comment]
Hi @ghostintheshellarise,

we provide two versions: the CPU version and the mac version to use locally.
If you have a hard to progress, please let us know.

**Comment by mjeensung** [comment]
Hi @ghostintheshellarise 

Could you try https://github.com/dmis-lab/BERN2/blob/main/scripts/run_bern2_cpu.sh?
It will allow BERN2 to run without GPU/CUDA.
