### ISSUE TITLE
Resource file network error

### ISSUE THREAD

**Issue by combax** [dmis-lab/BERN2#35]
There is no problem with my internet coz other big files are downloaded with ease, only this resources_v1.1.tar.gz file stops at 89% and shows network error.

**Comment by minstar** [comment]
Sorry for the inconvenience and late reply.

We have tried to download the resource file and it did well on our trial.
Thus, we really don't know the reason why it doesn't work in your environment.
We suggest a download link of the resource file on our google drive and the URL is as follows,
https://drive.google.com/file/d/1LsXcXDzgjY9mnOyDmrX1HsMfewYMKvN9/view?usp=sharing

If you still have any problems downloading our link, please let us know.

**Comment by combax** [comment]
Alright I'll download the file in different environment and update you later.
