### ISSUE TITLE
I'm running BERN2 but server can't be reached

### ISSUE THREAD

**Issue by Ufifus** [dmis-lab/BERN2#37]
Running:
bash run_bern2_cpu.sh
[18/Oct/2022 17:29:56.854986] BERN2 LOADING..
./output 0
./resources/GNormPlusJava/input 0
./resources/tmVarJava/input 0
start loading neural normalizer..
neural_disease_normalizer is loaded.. model=dmis-lab/biosyn-sapbert-bc5cdr-disease , dictionary=resources/normalization/normalizers/neural_norm_caches/dict_Disease_20210630.txt.pk
Arguments:
	host: 0.0.0.0
	port: 8888
	mtner_home: ./multi_ner
	mtner_port: 18894
	gnormplus_home: ./resources/GNormPlusJava
	gnormplus_port: 18895
	tmvar2_home: ./resources/tmVarJava
	tmvar2_port: 18896
	cache_host: localhost
	cache_port: 27017
	gene_norm_port: 18888
	disease_norm_port: 18892
	use_neural_normalizer: True
	keep_files: False
	front_dev: False
	no_cuda: True
[18/Oct/2022 17:31:25.741639] BERN2 LOADING..
./output 0
./resources/GNormPlusJava/input 0
./resources/tmVarJava/input 0
start loading neural normalizer..
neural_disease_normalizer is loaded.. model=dmis-lab/biosyn-sapbert-bc5cdr-disease , dictionary=resources/normalization/normalizers/neural_norm_caches/dict_Disease_20210630.txt.pk

Error:
>>> response = requests.get('http://localhost:8888/pubmed/30429607,29446767).json()
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /pubmed/30429607,29446767 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f00d7cad9c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Maybe i did something wrong, thank you for your time.

**Comment by mjeensung** [comment]
Hi @Ufifus 
Sorry for the late response.

Could you check if all processes for running BERN2 are alive? 
```
ps auxww | grep ner_server.py
ps auxww | grep GNormPlusServer.main.jar
ps auxww | grep tmVar2Server.main.jar 
ps auxww | grep disease_normalizer_21.jar 
ps auxww | grep gnormplus-normalization_21.jar 
ps auxww | grep server.py
```

**Comment by mjeensung** [comment]
If you have any follow-up questions, please re-open this issue.

**Comment by Ufifus** [comment]
Sorry for the latest response too)
Your answer helps me, on processes just dont working:
artem     105084  0.0  0.0  17872  2316 pts/1    S+   21:05   0:00 grep --color=auto ner_server.py
artem     105086  0.0  0.0  17884  2256 pts/1    S+   21:05   0:00 grep --color=auto GNormPlusServer.main.jar
artem     105088  0.0  0.0  17880  2300 pts/1    S+   21:05   0:00 grep --color=auto tmVar2Server.main.jar
artem     105090  0.0  0.0  17880  2280 pts/1    S+   21:05   0:00 grep --color=auto disease_normalizer_21.jar
artem     105092  0.0  0.0  17884  2336 pts/1    S+   21:05   0:00 grep --color=auto gnormplus-normalization_21.jar
artem     105094  0.0  0.0  17872  2448 pts/1    S+   21:05   0:00 grep --color=auto server.py
 
How much memory RAM i need for running BERN2 on CPU/GPU? Thanks you
