### ISSUE TITLE
Errors while extracting resource-file

### ISSUE THREAD

**Issue by Bancherd-DeLong** [dmis-lab/BERN2#40]
Hi:

Thank you very much for sharing your excellent work.  While trying to extract the resource file, I ran into this error.  Any suggestions as to the cause(s)?

tar -zxvf resources_v1.1.b.tar.gz
.
.

resources/tmVarJava/Database/var2rs_Xm.db
resources/tmVarJava/Database/gene2rs.db
tar: Skipping to next header
tar: A lone zero block at 22871798
tar: Exiting with failure status due to previous errors
.

Regards,

Bancherd

**Comment by mjeensung** [comment]
Hi @Bancherd-DeLong 

I guess the file you have might be corrupted for some reason.
Could you check md5sum of it?
It should be 'c0db4e303d1ccf6bf56b42eda2fe05d0'.

```
$ md5sum resources_v1.1.b.tar.gz
c0db4e303d1ccf6bf56b42eda2fe05d0  resources_v1.1.b.tar.gz
```

**Comment by Bancherd-DeLong** [comment]
Thank you for the response.  It was definitely corrupted.  I tried multiple times with varying incorrect md5sum.  This is the furthest that I got to:
![extract](https://user-images.githubusercontent.com/30105665/203670989-20e9191c-0ef3-48ca-90d7-a7d552b53857.png)

So I have folders tmVarJava and GNormPlusJava, but NOT normalizers +

Thank you.

**Comment by mjeensung** [comment]
We uploaded the resource file on google drive as well.

https://drive.google.com/file/d/1LsXcXDzgjY9mnOyDmrX1HsMfewYMKvN9/view?usp=sharing

Could you download the file from the link above and try decompressing it again?

**Comment by Bancherd-DeLong** [comment]
Got it, it Works!
Thank you very much!

Bancherd
PS. I will close the issue.

**Comment by Bancherd-DeLong** [comment]
Got it through the google-drive.  IT works!
Thank you very much.

Best Regards,

Bancherd
