### ISSUE TITLE
Google Drive Link Not Found

### ISSUE THREAD

**Issue by marjoleinpnnl** [dmis-lab/BERN2#44]
Hello, the link to google drive seems to be "not found": https://drive.google.com/file/d/1LsXcXDzgjY9mnOyDmrX1HsMfewYMKvN9/view?usp=sharing 
Is it just me? Thanks for making this a public resource!

**Comment by minstar** [comment]
Sorry for the inconvenience.

We suggest another google drive for the requested resources.
https://drive.google.com/file/d/147b3OhU4IdQi121ZBUSqO1XKdKoXE5DK/view?usp=sharing
If it doesn't work for you, please let us know.

**Comment by alexander-belikov** [comment]
the current link is not public :/

**Comment by minstar** [comment]
Could you try once again?

I made it publicly.
