### ISSUE TITLE
Annotation of pubmed23 baseline

### ISSUE THREAD

**Issue by yuch25** [dmis-lab/BERN2#47]
Hi, I want to know if the annotation of the pubmed23 baseline is on a plan.  

If I want BioEntities in PubMed23, should I wait for your update or simply use pubmed22-baseline and combine it with BERN2-API?

Thank you.

**Comment by mjeensung** [comment]
Hi,

While we were considering working on PubMed23, we do not currently have a specific plan due to resource constraints. 

However, we suggest that you annotate it by installing BERN2 on your local environment.
