### ISSUE TITLE
You SSL certificate for http://bern2.korea.ac.kr has expired

### ISSUE THREAD

**Issue by rlaurie** [dmis-lab/BERN2#49]
Trying to use API in Google Colaboratory and it will not process due to the following error:
SSLCertVerificationError

**Comment by mjeensung** [comment]
Hi,

BERN2 operates on the HTTP protocol, which means that an SSL certificate is not mandatory. However, if you're still experiencing issues, you can try setting `verify=False`.

https://stackoverflow.com/questions/74046266/python-get-request-ssl-sslcertverificationerror-ssl-certificate-verify-faile
