### ISSUE TITLE
bug in PMID REST-API: long publication titles get truncated after line break

### ISSUE THREAD

**Issue by koernel2** [dmis-lab/BERN2#53]
The code of function `get_text_data_from_pubmed()` in `bern2.py` only considers lines to be the publication title that are explicitly tagged by starting with "TI". However, longer titles are separated over multiple lines just as is the case with abstract text.

Example (see https://pubmed.ncbi.nlm.nih.gov/22588882/?format=pubmed) :

"...
TI  - Kinetics of inhibitor cycling underlie therapeutic disparities between 
      EGFR-driven lung and brain cancers.
..."

The current parser will only extract "Kinetics of inhibitor cycling underlie therapeutic disparities between" as the title. 

I suggest to fix this by simply applying the same approach you took for dealing with multi-line abstracts (code below, added code lines flagged by comment).
In addition, when fusing title and abstract before the combined text is processed by BERN2, please add a full stop "." at the end of the title so the LLM can recognize them as separate sentences.

```python
if status_code == 200:
        is_abs = False
        is_title = False                                    # added 
        for line in response.text.split("\n"):
            if line.startswith("TI  -"):
                is_title = True                             # added
                title = line.replace("TI  -", "").strip()
            elif is_title and line.startswith("      "):    # added
                title += " " + line.strip()                 # added
            elif line.startswith("AB  -"):
                is_title = False                            # added
                is_abs = True
                abstract += line.replace("AB  -", "").strip()
            elif is_abs and line.startswith("      "):
                abstract += " " + line.strip()
            else:
                is_abs = False
            #print (line)    
        text = title + " " + abstract
```

**Comment by mjeensung** [comment]
Thanks for reporting the issue!

I've merged the updated lines your suggested into our code.
https://github.com/dmis-lab/BERN2/commit/58eb6c341e803a7100d6b654a39eb17421f92e3a
