### ISSUE TITLE
Restful API method throwing 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by bikashpanda11** [dmis-lab/BERN2#64]
Calling the BERN2 restful API method using python requests is giving 500 internal server error. Even the demo on the BERN2 website is not working and is throwing 500 internal server errors.

**Comment by 1storik** [comment]
I have the same problem, if you find a solution please let me know

**Comment by mjeensung** [comment]
Apologies for the inconvenience. We have restarted the BERN2 server, and it is now working.

**Comment by 1storik** [comment]
> Apologies for the inconvenience. We have restarted the BERN2 server, and it is now working.

Thank you

**Comment by bikashpanda11** [comment]
Thank you for restarting the server. However, its giving the same error again since yesterday. Please restart the server. Thanks in advance!!

**Comment by Wunderkiki** [comment]
The api linking still fails today.
