### ISSUE TITLE
Getting Timeout Errors while using Restful API method

### ISSUE THREAD

**Issue by bikashpanda11** [dmis-lab/BERN2#66]
When running the code in a loop, the first session works however post that it gives timeout errors. Even the BERN2 page gives this error -- ERROR: 0 timeout.

**Comment by bikashpanda11** [comment]
Getting the same error, since last couple of days.

**Comment by bikashpanda11** [comment]
Please restart the server. Getting timeout errors for the last couple of days.

**Comment by Khyati-Microcrispr** [comment]
hey is this error got resolved, I am gettting the same error !
