### ISSUE TITLE
Bern2 is failing in API instance

### ISSUE THREAD

**Issue by bikashpanda11** [dmis-lab/BERN2#71]
BERN2 is failing while running it using API in Python. Also, the BERN2 example on the webpage has been giving Timeout errors since the last week. Please restart the server!

**Comment by mjeensung** [comment]
@hoonick7

**Comment by hoonick7** [comment]
Hi, @bikashpanda11 !

Thank you for the restart request. I have restarted the server about 10 hours ago. While the API seems to be working fine now, the demo webpage is still experiencing issues. I am currently investigating this and will take action to resolve it as soon as possible. In the meantime, if you encounter any further problems with the API, please feel free to comment on this issue. Thank you for your patience, and I will update you once the demo page is fully operational.

**Comment by hoonick7** [comment]
The demo webpage is now operational as of this moment. It appears the delay in restarting the services was caused by the aging server hosting the API. If you experience any further inconveniences, please feel free to report them at any time. Thank you for your cooperation.

**Comment by faridan** [comment]
@hoonick7 I'm still getting the below error in the middle of running:
`ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

**Comment by hoonick7** [comment]
Hi, @faridan !

Thank you for reporting the error. I have restarted the server once again to address the issue. It seems there might be a conflict with other services running on the same server, which could be causing the disconnection. Please let me know if the problem persists after the reboot, and I will investigate further. Thank you for your understanding!

**Comment by bikashpanda11** [comment]
Hi @hoonick7. Thank you for restarting the server. However, I am still facing issues. It takes time to run a single text query and at the end giving Connection aborted error message. I would be really grateful if you could please help me with this.

**Comment by hoonick7** [comment]
@bikashpanda11 

Thank you for your continued patience. While the aging server has been causing slower inference times recently, I’ve noticed the current delay is significantly longer than before. There’s also the connection error you mentioned, which I’m currently investigating. I’m looking into both issues and will provide an update once I have more details. Apologies for the inconvenience, and thank you for your understanding.

**Comment by bikashpanda11** [comment]
Thank you, @hoonick7, for your prompt reply and all the help!

**Comment by hoonick7** [comment]
@bikashpanda11 

I just reviewed the system and made some adjustments. It seems to be responding faster now. I’m still looking into the connection error issue. If the problem persists, I can investigate further.

**Comment by bikashpanda11** [comment]
Thank you @hoonick7. The API requests are working well.
